name: "Test Action"
on:
  pull_request_target:

jobs:
  # test action works running from the graph
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yevgenypats/is-organization-member@23a28bea2c2d4069afbb250ceac8c94ffe990e8d
        id: is_organization_member
        with:
          organization: cloudquery
          username: ${{ github.event.pull_request.user.login }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Log Result
        run: |
          result=${{steps.is_organization_member.outputs.result}}
          echo "$result"
      - name: Fail if not member
        run: |
          result=${{ steps.is_organization_member.outputs.result }}
          if [ $result == true ]; then
              echo user is not part of org
              exit 1
          fi
      - name: Create Comment 2
        run: echo User Does Belong to cloudquery
