name: Sync Files
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
      - name: Run GitHub File Sync
        uses: cloudquery/repo-file-sync-action@751ebc62d2aaff3b84514dd3203d20c968d945ed
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          BRANCH_PREFIX: custom-branch
          PR_LABELS: chore
          COMMIT_PREFIX: "chore: "
          OVERWRITE_EXISTING_PR: true
